### ISSUE TITLE
Cannot read properties of undefined (reading 'map')

### ISSUE THREAD

**Issue by linonetwo** [tiddly-gittly/super-tag#7]
```
caught TypeError: Cannot read properties of undefined (reading 'map')
    at eval (index.js:44:25)
    at Array.map (<anonymous>)
    at getSuperTagTraits (index.js:42:29)
    at getFullSchemaFromCurrentTiddler (index.js:89:21)
    at SupertagFormWidget.render (index.js:122:45)
    at Widget.renderChildren (widget.js:632:15)
    at ElementWidget.render (element.js:84:7)
    at Widget.renderChildren (widget.js:632:15)
    at ListItemWidget.render (list.js:342:7)
    at Widget.renderChildren (widget.js:632:15)
```

```
const traits = tags.map((traitTitle) => {
```

<img width="1023" alt="截屏2023-05-29 16 18 44" src="https://github.com/tiddly-gittly/super-tag/assets/3746270/8b77da01-cf3f-4bad-b65e-6d7984a7906b">

**Comment by linonetwo** [comment]
![截屏2023-05-29 16 19 50](https://github.com/tiddly-gittly/super-tag/assets/3746270/67563674-16e3-4cd2-bf9a-b05e478dd309)
